function Hd = derivative
%DERIVATIVE Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.13 and the Signal Processing Toolbox 6.16.
%
% Generated on: 04-Nov-2012 13:24:39
%

% Equiripple Differentiator filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 360;  % Sampling Frequency

N = 10;              % Order
F = [0 0.5 0.55 1];  % Frequency Vector
A = [0 1 0 0];       % Amplitude Vector
W = [1 1];           % Weight Vector

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, F/(Fs/2), A, W, 'differentiator');
Hd = dfilt.dffir(b);

% [EOF]
